# **Assignment** #**1** 
# **PIAIC99938** 
## **Hamad** **Younis**


In [ ]:
import numpy as np
np.__version__


'1.19.4'

In [ ]:
arr = np.array([0,1,2,3,4,5,6,7,8,9]) # simple 10 element 1D array
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Similar to other C Style languages index start with zero

*   To access first element 
*   To access last element



In [ ]:
print(arr[0]) # first element
print(arr[9]) # last element

0
9


Trigonometric functions

In [ ]:
# Calculate sine, cosine, and tangent of x, element-wise.
x = np.array([0., 1., 30, 90])
print ("sine:", np.sin(x))
print ("cosine:", np.cos(x))
print ("tangent:", np.tan(x))

sine: [ 0.          0.84147098 -0.98803162  0.89399666]
cosine: [ 1.          0.54030231  0.15425145 -0.44807362]
tangent: [ 0.          1.55740772 -6.4053312  -1.99520041]


In [ ]:
# Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.
x2 = np.array([-1., 0, 1.])
print ("inverse sine:", np.arcsin(x2))
print ("inverse cosine:", np.arccos(x2))
print ("inverse tangent:", np.arctan(x2))

inverse sine: [-1.57079633  0.          1.57079633]
inverse cosine: [3.14159265 1.57079633 0.        ]
inverse tangent: [-0.78539816  0.          0.78539816]


In [ ]:
#  Convert angles from radians to degrees.
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

out1 = np.degrees(x)
out2 = np.rad2deg(x)
assert np.array_equiv(out1, out2)
print (out1)

[-180.  -90.   90.  180.]


In [ ]:
# Convert angles from degrees to radians.
x = np.array([-180.,  -90.,   90.,  180.])

out1 = np.radians(x)
out2 = np.deg2rad(x)
assert np.array_equiv(out1, out2)
print (out1)

[-3.14159265 -1.57079633  1.57079633  3.14159265]


Hyperbolic functions



In [ ]:
# Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.
x = np.array([-1., 0, 1.])
print ("Hyperbolic sine:",np.sinh(x))
print ("Hyperbolic cos:",np.cosh(x))
print ("Hyperbolic tan:",np.tanh(x))

Hyperbolic sine: [-1.17520119  0.          1.17520119]
Hyperbolic cos: [1.54308063 1.         1.54308063]
Hyperbolic tan: [-0.76159416  0.          0.76159416]


In [ ]:
# Rounding
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])

out1 = np.around(x)
out2 = np.floor(x)
out3 = np.ceil(x)
out4 = np.trunc(x)
out5 = [round(elem) for elem in x]

print ("Around:",out1)
print ("Floor:",out2)
print ("Ceil:",out3)
print ("Trunc:",out4)
print ("Round:",out5)

Around: [ 2.  2.  2.  3. -2. -2. -3.]
Floor: [ 2.  1.  2.  2. -3. -3. -3.]
Ceil: [ 3.  2.  3.  3. -2. -2. -2.]
Trunc: [ 2.  1.  2.  2. -2. -2. -2.]
Round: [2, 2, 2, 3, -2, -2, -3]


In [ ]:
# Calculate the difference between neighboring elements, element-wise.
x = np.array([1, 2, 4, 7, 0])
print ("Difference:",np.diff(x))

Difference: [ 1  2  3 -7]


In [ ]:
# the cross product of x and y.
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print ("Cross product:",np.cross(x, y))

Cross product: [-3  6 -3]


Exponents and logarithms


In [ ]:
# Compute $e^x$, element-wise
x = np.array([1., 2., 3.], np.float32)

out = np.exp(x)
print ("Exponential:",out)

Exponential: [ 2.718282   7.3890557 20.085537 ]


In [ ]:
# Compute natural, base 10, and base 2 logarithms of x element-wise.
x = np.array([1, np.e, np.e**2])

print ("Natural log =", np.log(x))
print ("Common log =", np.log10(x))
print ("Base 2 log =", np.log2(x))

Natural log = [0. 1. 2.]
Common log = [0.         0.43429448 0.86858896]
Base 2 log = [0.         1.44269504 2.88539008]


Arithmetic operations


In [ ]:
# Add x and y element-wise
x = np.array([5, 6, 7])
y = np.array([3, 4, 6])

out1 = np.add(x, y)
out2 = x + y
assert np.array_equal(out1, out2)
print ("Addtion Result:",out1)

Addtion Result: [ 8 10 13]


In [ ]:
# Subtract y from x element-wise.
x = np.array([3, 4, 5])
y = np.array(3)

out1 = np.subtract(x, y)
out2 = x - y 
assert np.array_equal(out1, out2)
print ("Subtraction Result:",out1)

Subtraction Result: [0 1 2]


In [ ]:
# Multiply x by y element-wise.
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])

out1 = np.multiply(x, y)
out2 = x * y 
assert np.array_equal(out1, out2)
print ("Multiplication Result",out1)

Multiplication Result [ 3  0 -5]


In [ ]:
# Divide x by y element-wise in two different ways.
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])

out1 = np.true_divide(x, y)
out2 = x / y 
assert np.array_equal(out1, out2)
print ("True Divison Result",out1)

out3 = np.floor_divide(x, y)
out4 = x // y
assert np.array_equal(out3, out4)
print ("Floor Divison Result",out3)

True Divison Result [3.         2.         1.66666667]
Floor Divison Result [3. 2. 1.]


In [ ]:
# Compute numerical negative value of x, element-wise.
x = np.array([1, -1])

out1 = np.negative(x)
out2 = -x
assert np.array_equal(out1, out2)
print ("Negative Result",out1)

Negative Result [-1  1]


In [ ]:
# Compute the reciprocal of x, element-wise.
x = np.array([1., 2., .2])

out1 = np.reciprocal(x)
out2 = 1/x
assert np.array_equal(out1, out2)
print ("Reciprocal Result",out1)

Reciprocal Result [1.  0.5 5. ]


In [ ]:
# Compute $x^y$, element-wise.
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])

out = np.power(x, y)
print ("Power Result",out)

Power Result [[ 1  4]
 [ 3 16]]


In [ ]:
# Compute the remainder of x / y element-wise in two different ways.
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2

out1 = np.mod(x, y)
out2 = x % y
assert np.array_equal(out1, out2)
print (out1)

out3 = np.fmod(x, y)
print( out3)

[1 0 1 1 0 1]
[-1  0 -1  1  0  1]


In [ ]:
# Compute square root of x element-wise.
x = np.array([1., 4., 9.])

out = np.sqrt(x)
print("Square Root:",out)

Square Root: [1. 2. 3.]


In [ ]:
# Compute the absolute value of x.
x = np.array([[1, -1], [3, -3]])

out = np.abs(x)
print("Absolute:",out)

Absolute: [[1 1]
 [3 3]]


In [ ]:
# Compute the square of x, element-wise.
x = np.array([1, 2, -1, 4,6])

out1 = np.square(x)
out2 = x * x
assert np.array_equal(out1, out2)
print("Square:",out1)

Square: [ 1  4  1 16 36]


In [ ]:
import numpy as np
in_num1 = 10
in_num2 = 50
  
print ("Input  number1 : ", in_num1) 
print ("Input  number2 : ", in_num2)  
    
out_num = np.maximum(in_num1, in_num2)  
print ("maximum of 10 and 50 : ", out_num)  

Input  number1 :  10
Input  number2 :  50
maximum of 10 and 50 :  50


In [50]:
import numpy as np 
in_num1 = 5
in_num2 = 10
  
print ("Input  number1 : ", in_num1) 
print ("Input  number2 : ", in_num2)  
    
out_num = np.minimum(in_num1, in_num2)  
print ("minimum of 5 and 10 : ", out_num)  

Input  number1 :  5
Input  number2 :  10
minimum of 5 and 10 :  5


In [53]:
# real and imginary part of the complex argument.
a = np.array([1+2j, 3+4j, 5+6j])
print ("Real Number : ", a.real) 
print ("Imaginary Number: ", a.imag) 

Real Number :  [1. 3. 5.]
Imaginary Number:  [2. 4. 6.]


In [56]:
# the complex conjugate, element-wise
x=np.conjugate(1+2j)
print ("Conjugate: ", x) 

Conjugate:  (1-2j)


In [58]:
# the linear convolution, element-wise
y=np.convolve([1, 2, 3], [0, 1, 0.5])
print ("linear convolution: ", y) 

linear convolution:  [0.  1.  2.5 4.  1.5]


In [59]:
# the LCM, element-wise
z=np.lcm(12, 20)
print ("LCM: ", z) 

LCM:  60


In [60]:
# the GCD, element-wise
v=np.gcd(12, 20)
print ("GCD: ", v) 

GCD:  4


In [66]:
#  element-wise True where signbit is set (less than zero).
a=np.signbit(-1.2)
b=np.signbit(np.array([1, -2.3, 2.1]))
print ("Signbit: ", a) 
print ("Signbit: ", b) 

Signbit:  True
Signbit:  [False  True False]


In [69]:
	
# Element-wise maximum of array elements.
np.fmax([2, 3, 4], [1, 5, 2])

array([2, 5, 4])

In [70]:
	
# Element-wise minimum of array elements.
np.fmin([2, 3, 4], [1, 5, 2])

array([1, 3, 2])

In [73]:
# Calculate Gradient.
f = np.array([1, 2, 4, 7, 11, 16], dtype=float)
np.gradient(f)

array([1. , 1.5, 2.5, 3.5, 4.5, 5. ])

In [74]:
# Return element-wise remainder of division.
np.remainder([4, 7], [2, 3])

array([0, 1])

In [76]:
# Return the fractional and integral parts of an array, element-wise..
np.modf([0, 3.5])

(array([0. , 0.5]), array([0., 3.]))